# Generated by Django 3.2.3 on 2022-10-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Рецепт в избранном у пользователя', 'verbose_name_plural': 'Рецепт в избранном у пользователей'},
        ),
    ]
