# Generated by Django 3.2.3 on 2022-10-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_users_cannot_subscribe_to_themselves'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='users_cannot_subscribe_to_themselves',
        ),
    ]
